import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header >



          <nav >
            <div class="flex   justify-between items-center mx-auto max-w-screen-xl p-4">
              <a href="https://flowbite.com" class="flex items-center space-x-3 ">
                <img src="https://flowbite.com/docs/images/logo.svg" class="h-8 " alt="Flowbite Logo" />
                <span class=" self-center text-3xl font-semibold whitespace-nowrap text-gega-red bg-gradient-to-r from-indigo-500">NETFLIX</span>
              </a>
              <div class="flex items-center  ">
                <input class="bg-black  border-solid border-2 border-gega-red mr-3" placeholder="search" type="text" />
                <a href="#" class=" bg-gega-red md:w-20 text-center h-7  text-black   hover:underline">Login</a>
              </div>
            </div>
          </nav>
          <nav >
            <div class="max-w-screen-xl px-4 py-3 mx-auto">
              <div class="flex  ">
                <ul class="flex flex-row  mt-0 space-x-8  mx-auto md:text-xl ">
                  <li>
                    <a href="/"  >HOME</a>

                  </li>
                  <li>
                    <a href="/science">SCIENCE</a>
                  </li>
                  <li>
                    <a href="/history">HISTORY</a>
                  </li>
                  <li>
                    <a href="/marvel">MARVEL</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>


        </header>
        <main>{children}</main>
        <footer>
          <span class="block text-sm text-gega-red text-center ">© 2024 <a href="https://github.com/BURAKCIDA?tab=repositories" class="hover:underline">BURAK CIDA</a></span>
        </footer>
      </body>
    </html >
  );
}
